services:
  app:
    build: .
    depends_on:
      - postgres
      - redis
      - exchange1
      - exchange2
      - exchange3
    ports:
      - "8080:8080"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: marketuser
      POSTGRES_PASSWORD: marketpass
      POSTGRES_DB: marketdb
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - ./logs:/app/logs

  postgres:
    image: postgres:15-alpine
    container_name: postgres
    environment:
      POSTGRES_USER: marketuser
      POSTGRES_PASSWORD: marketpass
      POSTGRES_DB: marketdb
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  exchange1:
    image: exchange1
    container_name: exchange1
    ports:
      - "40101:40101"

  exchange2:
    image: exchange2
    container_name: exchange2
    ports:
      - "40102:40102"

  exchange3:
    image: exchange3
    container_name: exchange3
    ports:
      - "40103:40103"

volumes:
  pgdata:
